version: '3.4'


services:
  redis-master:
    container_name: redis-master
    image: redis:5.0.3-alpine3.9
    ports:
      - "6379:6379"
  redis-slave1:
    container_name: redis-slave1
    image: redis:5.0.3-alpine3.9
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    ports:
      - "6380:6379"
  redis-slave2:
    container_name: redis-slave2
    image: redis:5.0.3-alpine3.9
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    ports:
      - "6381:6379"
